name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install

      - name: Deploy 🚀
        run: npx ng deploy --no-silent --base-href=/EzyFS-Frontend/ --name="Mellywins" --email="zouaghi.wow1919@gmail.com"
